POST http://13.125.106.21:8080/posts/3/comments
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJoeXVub2guam9AZ21haWwuY29tIiwiZXhwIjoxNjU4OTM1OTg0fQ.bypFwQKUNGoVjMU88TSeCw7EO0ExUHAIwm-Pc0fWvLqVR0EJJe6TmD-QkPhN8czuD1GWUb3qbm1eLgPikciZJw
refresh_token: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJoeXVub2guam9AZ21haWwuY29tIiwiZXhwIjoxNjU5MTg5MTg0fQ.mOtfQpPSnbYatsWdWlTsGAuyECOSbqGT_L6Nc5YmmwKffdB6B9cIo1p-3kK9GltClzU0kenRebqCTNe1g2pDGg

{
  "content": "댓글6"
}

###
GET http://13.125.106.21/posts/2/comments
Content-Type: application/json