POST http://13.125.106.21:8080/user/signup
Content-Type: application/json

{
  "username": "jahyunnine@gmail.com",
  "password": "qwe123!!",
  "rePassword": "qwe123!!",
  "nickname": "테스트용"
}

###

POST http://13.125.106.21:8080/login
Content-Type: application/json

{
  "username": "jahyunnine@gmail.com",
  "password": "qwe123!!"
}
###
GET http://13.125.106.21:8080/user/info
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJqYWh5dW5uaW5lQGdtYWlsLmNvbSIsImV4cCI6MTY1ODkwNjIxNX0.2pumIeH7kepZ0mT_PZf8X7OUH5XANkS8z0SlADtnbAm4aghV-dmFwej8FD1ZRVgb7mQJci9Pe6klZmWnFFLzeg
refresh_token: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJqYWh5dW5uaW5lQGdtYWlsLmNvbSIsImV4cCI6MTY1OTE1OTQxNn0.y0RaPM2TwY4Nm0QROK5U2Bwadeu3lkNnDFCDt7gKwOjXqIacLWer6y-66HUHQ15wZW4Od_1Od7jVr9x2u6BYkw
###

POST http://13.125.106.21:8080/logout
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJqYWh5dW5uaW5lQGdtYWlsLmNvbSIsImV4cCI6MTY1ODkwNTg4Nn0.dA43g25nX1-W5TIP5qvNPeoaAq8KCKlx3qrUY2w9aCoUTV9llGLHjna9SUrGDBLOmlhZoO5Kr90yKqWk8Ed2sg
refresh_token: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJqYWh5dW5uaW5lQGdtYWlsLmNvbSIsImV4cCI6MTY1OTE1OTA4Nn0.Gt4fTh93Ei41FO1pZdS5TOnmL9ILJrS4TsxbiiC_Om1Ru7Yoqx6l-H8KRdgEKNRgxd6RV0Xau6kvdFn8Sdf7hg
