spring:
  profiles:
    active: DB, KEY, AWS

  jackson:
    time-zone: Asia/Seoul

  application:
    name: limsPhoto
management:
  endpoints:
    web:
      exposure:
        include: "prometheus"
  metrics:
    tags:
      application: ${spring.application.name}